"""Aion level format parsers."""

from .brush import BrushList, BrushMeshEntry, BrushNodePlacement, parse_brush_lst
from .cga_entities import (
    CgaEntities,
    CgaEntityCandidate,
    cga_entities_to_dict,
    parse_mission_cga_entities,
)
from .leveldata import LevelData, LevelInfo, SurfaceType, parse_leveldata
from .liquid_surface import (
    LIQUID_KIND_AUTO,
    LIQUID_KIND_LAVA,
    LIQUID_KIND_UNKNOWN,
    LIQUID_KIND_WATER,
    LIQUID_PRESET_AUTO,
    LIQUID_PRESET_LAVA_EMISSIVE,
    LIQUID_PRESET_NORMAL,
    LIQUID_PRESET_TRANSPARENT,
    LiquidSurfaceRecipe,
    LiquidTextureCandidate,
    build_liquid_surface_recipe,
    classify_liquid_texture_role,
    extract_liquid_references,
    infer_liquid_kind,
    infer_liquid_kind_from_text,
    liquid_surface_recipe_to_dict,
    resolve_liquid_texture_candidates,
)
from .mission_placeables import (
    MissionPlaceableCandidate,
    MissionPlaceables,
    is_suspicious_static_cgf_skip,
    mission_asset_has_runtime_segment,
    mission_placeables_to_dict,
    parse_mission_placeables,
)
from .objects import ObjectsList, ObjectPlacement, parse_objects_lst
from .particle_effects import (
    EntityContextParticleEffect,
    EntityContextParticleEffects,
    ParticleTextureReference,
    PrtEmitterRecord,
    PrtEffectDefinition,
    parse_entitycontext_particle_effects,
    parse_prt_effect_definition,
    particle_effect_library_path,
    particle_effects_to_dict,
    prt_effect_definition_to_dict,
    resolve_particle_effect_definition,
)
from .static_lights import (
    STATIC_LIGHT_FLOAT_COUNT,
    StaticDeferredLight,
    StaticDeferredLights,
    parse_static_deferred_lights,
    static_deferred_lights_to_dict,
)
from .terrain import LandMap, LandMapSample, parse_land_map_h32
from .terrain_blending import (
    TerrainBlendWeights,
    TerrainSampleBlendWeights,
    build_terrain_preview_blend_weights,
)
from .terrain_materials import (
    TerrainMaterialInventory,
    TerrainMaterialUsage,
    build_terrain_material_inventory,
)

__all__ = [
    "BrushList",
    "BrushMeshEntry",
    "BrushNodePlacement",
    "CgaEntities",
    "CgaEntityCandidate",
    "LandMap",
    "LandMapSample",
    "LevelData",
    "LevelInfo",
    "LIQUID_KIND_AUTO",
    "LIQUID_KIND_LAVA",
    "LIQUID_KIND_UNKNOWN",
    "LIQUID_KIND_WATER",
    "LIQUID_PRESET_AUTO",
    "LIQUID_PRESET_LAVA_EMISSIVE",
    "LIQUID_PRESET_NORMAL",
    "LIQUID_PRESET_TRANSPARENT",
    "LiquidSurfaceRecipe",
    "LiquidTextureCandidate",
    "MissionPlaceableCandidate",
    "MissionPlaceables",
    "ObjectsList",
    "ObjectPlacement",
    "EntityContextParticleEffect",
    "EntityContextParticleEffects",
    "ParticleTextureReference",
    "PrtEmitterRecord",
    "PrtEffectDefinition",
    "STATIC_LIGHT_FLOAT_COUNT",
    "SurfaceType",
    "StaticDeferredLight",
    "StaticDeferredLights",
    "TerrainBlendWeights",
    "TerrainMaterialInventory",
    "TerrainMaterialUsage",
    "TerrainSampleBlendWeights",
    "build_terrain_material_inventory",
    "build_terrain_preview_blend_weights",
    "build_liquid_surface_recipe",
    "cga_entities_to_dict",
    "classify_liquid_texture_role",
    "extract_liquid_references",
    "infer_liquid_kind",
    "infer_liquid_kind_from_text",
    "is_suspicious_static_cgf_skip",
    "mission_asset_has_runtime_segment",
    "parse_brush_lst",
    "parse_mission_cga_entities",
    "parse_land_map_h32",
    "parse_leveldata",
    "parse_mission_placeables",
    "parse_objects_lst",
    "parse_entitycontext_particle_effects",
    "parse_prt_effect_definition",
    "parse_static_deferred_lights",
    "liquid_surface_recipe_to_dict",
    "mission_placeables_to_dict",
    "particle_effect_library_path",
    "particle_effects_to_dict",
    "prt_effect_definition_to_dict",
    "resolve_particle_effect_definition",
    "resolve_liquid_texture_candidates",
    "static_deferred_lights_to_dict",
]
